adapter_name_or_path: saves/Qwen2.5-VL-3B-Instruct/lora/qwen2.5ko
cutoff_len: 2048
dataset_dir: data
ddp_timeout: 180000000
do_eval: true
eval_dataset: ko_eval
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
output_dir: saves/Qwen2.5-VL-3B-Instruct/lora/eval_qwen2.5_lora_ko
per_device_eval_batch_size: 32
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.95
template: qwen2_vl
top_p: 0.7
trust_remote_code: true
